### ISSUE TITLE
Double search bars

### ISSUE THREAD

**Issue by gniezen** [Amybo-org/pages#19]
I noticed that there are now two search bars at the top left and the top right of the page:

![image](https://github.com/user-attachments/assets/d3f5fa9f-54ef-467e-8d89-8c5a11fba6c3)

Neither of them seem to work and adversely affect the formatting of the header, hiding some of the content of the page. Which one should we try to fix - the Google one or the Algolia one?

**Comment by Aqueum** [comment]
Well spotted, it was only on Monday that I screwed this up, and I hadn't
yet noticed it myself.

I'm going to blame ChatGPT.  I hadn't used docsy in ages and couldn't get
it running locally.  Instead of fixing the errors and ignoring the
warnings, ChatGPT took me down a deep rabbit hole with an Aloglia warning.
It optimistically just keeps giving you more things to try, hence I rather
screwed it up & still haven't fixed the error.  I would assume Google would
give better results and help optimise our SEO if we can get that
fixed, their search option also looks better IMHO.  I was basically trying
to remove Algolia altogether as I hadn't come across it before and it's not
open source.  If moving from Google, I'd rather go with the likes of
elasticsearch.

If this is an easy fix for you then feel free, otherwise I'm doing an
AMYBO video as the next steps for the Water Climate Discussion report,
which we need to issue so we can pause our MailChimp subscription before it
renews on the weekend...  I can try to fix whatever I broke after that.

Kind regards

Martin

---
Martin Currie
Aqueum
+44 (0) 7544 113 102

The information in this email is confidential and solely for the use of the
intended recipient(s). If you receive this email in error, please notify
the sender and delete the email from your system immediately. In such
circumstances, you must not make any use of the email or its contents.
Aqueum is a trade mark of Aqueum Ltd, a Private Limited Company registered
in Scotland as company number SC572318 with registered office at 60
Ladeside, Newmilns, East Ayrshire, United Kingdom, KA16 9BE

**Comment by Aqueum** [comment]
This should be all fixed now.  I don't imagine our google search was ever working, but it does now, and Algolia has been removed.  It would be great if you could give it a quick test & see if all is as you would expect.
